# Generated by Django 5.2.3 on 2025-07-16 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('session_price', models.IntegerField()),
                ('cv', models.FileField(upload_to='cv_tutor')),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('desc', models.TextField()),
                ('profile_img', models.ImageField(upload_to='profile_image_tutor')),
                ('education_data', models.JSONField(help_text='List of education levels and subjects.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
