# Generated by Django 5.2.3 on 2025-07-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_tutor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_tutor',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='profile_tutor',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
