# Generated by Django 5.2.3 on 2025-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_profile_tutor_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_tutor',
            name='desc',
            field=models.TextField(blank=True, default='no description', null=True),
        ),
        migrations.AlterField(
            model_name='profile_tutor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile_tutor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile_tutor',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_image_tutor/default.jpg', null=True, upload_to='profile_image_tutor'),
        ),
    ]
