# Generated by Django 5.2.3 on 2025-07-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_alter_profile_tutor_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_tutor',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image_tutor'),
        ),
    ]
