# Generated by Django 5.2.3 on 2025-07-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_profile_tutor_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_tutor',
            name='location_access',
            field=models.BooleanField(default=False),
        ),
    ]
