# Generated by Django 5.2.4 on 2025-07-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_profile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_student',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
