# Generated by Django 5.2.4 on 2025-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_alter_profile_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_student',
            name='desc',
            field=models.TextField(blank=True, default='no description', null=True),
        ),
    ]
