# Generated by Django 5.2.4 on 2025-07-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_alter_profile_student_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_student',
            name='form_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile_tutor',
            name='form_completed',
            field=models.BooleanField(default=False),
        ),
    ]
