# Generated by Django 5.2.4 on 2025-07-26 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0010_profile_student_form_completed_and_more'),
        ('requestapp', '0009_requesting_tutor_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('req_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestapp.requesting_tutor')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile_student')),
                ('tutor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile_tutor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
