# Generated by Django 5.2.4 on 2025-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytutorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
