# Generated by Django 5.2.4 on 2025-07-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytutorapp', '0002_remove_feedback_user_feedback_is_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_feedback',
        ),
    ]
