# Generated by Django 5.2.4 on 2025-07-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytutorapp', '0003_remove_feedback_is_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
