# Generated by Django 5.2.4 on 2025-07-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_subjects_list'),
        ('profileapp', '0010_profile_student_form_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requesting_tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_rate', models.IntegerField()),
                ('session_start_date', models.DateField()),
                ('session_end_date', models.DateField()),
                ('session_time_from', models.TimeField()),
                ('session_time_to', models.TimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='profileapp.profile_student')),
                ('subject', models.ManyToManyField(to='categories.subjects_list')),
                ('tutor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieve_requests', to='profileapp.profile_tutor')),
            ],
        ),
    ]
