# Generated by Django 5.2.4 on 2025-07-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesting_tutor',
            name='session_type',
            field=models.CharField(default='offline', max_length=50),
        ),
    ]
