# Generated by Django 5.2.4 on 2025-07-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0002_requesting_tutor_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesting_tutor',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10),
        ),
    ]
