# Generated by Django 5.2.4 on 2025-07-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0003_requesting_tutor_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesting_tutor',
            name='session_type',
        ),
    ]
