# Generated by Django 5.2.4 on 2025-07-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0005_requesting_tutor_counter_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesting_tutor',
            name='counter_proposed_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
