# Generated by Django 5.2.4 on 2025-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0006_alter_requesting_tutor_counter_proposed_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesting_tutor',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
