# Generated by Django 5.2.4 on 2025-07-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0007_requesting_tutor_is_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesting_tutor',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
