# Generated by Django 5.2.4 on 2025-07-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0008_requesting_tutor_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesting_tutor',
            name='desc',
            field=models.TextField(blank=True, default='no desc', null=True),
        ),
    ]
