# Generated by Django 5.2.4 on 2025-07-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0009_requesting_tutor_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesting_tutor',
            name='is_feedback',
            field=models.BooleanField(default=True),
        ),
    ]
