# Generated by Django 5.2.4 on 2025-07-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0010_requesting_tutor_is_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesting_tutor',
            name='is_feedback',
        ),
    ]
